### ISSUE TITLE
On execute alters the orm is trying to use default pool mysql user to create tables inside log pool

### ISSUE THREAD

**Issue by iliyanm** [latolukasz/beeorm#7]
orm config:

```
orm:
  log_db_pool:
    mysql: ENV[LOG_DB_POOL_MYSQL]
  default:
    mysql: ENV[DEFAULT_MYSQL]
    sentinel:
      mymaster:3: ENV[REDIS_SENTINEL_MEMORY]
    locker: default
    local_cache: 1000
  variables_pool:
    sentinel:
      mymaster:2: ENV[REDIS_SENTINEL_PERSISTENT]
  streams_pool:
    sentinel:
      mymaster:1: ENV[REDIS_SENTINEL_PERSISTENT]
  search_pool:
    sentinel:
      mymaster:0: ENV[REDIS_SENTINEL_PERSISTENT]
```

env vars for mysql:
```
DEFAULT_MYSQL: fedshi:somepassM@tcp(192.168.181.36:3306)/fedshi
LOG_DB_POOL_MYSQL: fedshi_log:somepass@tcp(192.168.181.36:3306)/fedshi_log
```

these are env vars for default and log mysql
we have strange issue when using different mysql users for these 2 pools, as is the case in this example

```
Error 1142: CREATE command denied to user 'fedshi'@'ip-192-168-140-19.eu-north-1.compute.internal' for table '_log_default_menus'

2022/04/18 09:37:55 [Error]:
Error 1142: CREATE command denied to user 'fedshi'@'ip-192-168-140-19.eu-north-1.compute.internal' for table '_log_default_menus'
/builds/riverz/lys-backend/.go/pkg/mod/github.com/coretrix/hitrix@v1.1.10/service/component/error_logger/error_logger.go:135 (0xd41254)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/coretrix/hitrix@v1.1.10/service/component/error_logger/error_logger.go:78 (0xd40824)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/coretrix/hitrix@v1.1.10/service/component/error_logger/error_logger.go:65 (0xd406af)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/coretrix/hitrix@v1.1.10/recovery.go:21 (0x125e0b5)
/usr/local/go/src/runtime/panic.go:1038 (0x4334f4)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/latolukasz/beeorm@v1.3.22/db.go:297 (0xb04eda)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/coretrix/hitrix@v1.1.10/pkg/controller/dev_panel_controller.go:178 (0x12500c4)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x125d9e6)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/coretrix/hitrix@v1.1.10/gin.go:41 (0x125d9ce)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x125de8a)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/coretrix/hitrix@v1.1.10/recovery.go:25 (0x125de74)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x91fb30)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x91f798)
/builds/riverz/lys-backend/.go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x91f2d1)
/usr/local/go/src/net/http/server.go:2879 (0x6bba9a)
/usr/local/go/src/net/http/server.go:1930 (0x6b7147)
/usr/local/go/src/runtime/asm_amd64.s:1581 (0x464760)
```

so basically the issue is:
on execute alters the orm is trying to use default pool mysql user to create tables inside log pool
but this user does not have permissions for log pool, only for default pool

solution: orm should use log pool user and pass for mysql when working in log pool, not user and pass for default pool
